"""Regenerate requirements.lock: every dependency pinned by version AND by the
SHA-256 of every artefact PyPI serves for that version.

`requirements.txt` pins versions.  That is not enough for this repository:
round sixteen found that a BLAS thread-count change moved a bootstrap
percentile, and `verify_paper.py` tests rounding EQUALITY at the printed
precision rather than a tolerance.  A reader who installs "numpy==2.2.6" from
a different wheel, built against a different BLAS, can fail the checker while
computing nothing wrong.  Hashes close the first half of that gap; the
container definition and the thread pinning in REPRODUCE.md close the second.

    python scripts/make_lockfile.py          # writes ../requirements.lock
    python -m pip install --require-hashes -r requirements.lock
"""
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKGS = [
    "numpy==2.2.6", "pandas==2.3.1", "scipy==1.15.3", "scikit-learn==1.7.2",
    "matplotlib==3.10.5", "pyarrow==18.1.0", "joblib==1.5.2",
    "threadpoolctl==3.6.0", "python-dateutil==2.9.0.post0", "pytz==2025.2",
    "six==1.17.0", "cycler==0.12.1", "fonttools==4.59.0", "kiwisolver==1.4.8",
    "packaging==25.0", "pillow==11.3.0", "pyparsing==3.2.3",
    "contourpy==1.3.2", "tzdata==2025.2",
    # pandas routes DataFrame.to_latex through Styler, which imports jinja2.
    # Absent from the lock until round twenty-five, so a reader who followed
    # REPRODUCE.md exactly got an ImportError out of make_numbers.py -- the
    # first gate -- and no table.  markupsafe is jinja2's only dependency.
    "jinja2==3.1.6", "markupsafe==3.0.2",
    # requirements.txt has pinned these three since round eighteen and the lock
    # never carried them, so `--require-hashes` installed an environment that
    # requirements.txt says is incomplete.  pytest's absence was not loud:
    # make_numbers.count_tests falls back to counting `def test_` lines when
    # pytest will not collect, and that fallback wrote 42 into the manuscript
    # where the suite collects 108.  Their dependencies are pinned with it,
    # because --require-hashes refuses to resolve one it was not given.
    "pytest==8.4.2", "iniconfig==2.1.0", "pluggy==1.6.0", "pygments==2.19.2",
    ("exceptiongroup==1.3.0", 'python_version < "3.11"'),
    ("tomli==2.2.1", 'python_version < "3.11"'),
    "requests==2.32.5", "certifi==2025.8.3", "charset-normalizer==3.4.3",
    "idna==3.10", "urllib3==2.5.0",
    "pymupdf==1.26.6",
]
HEAD = """# requirements.lock -- every dependency pinned by version AND by the
# SHA-256 of every artefact PyPI serves for it.  Install with
#     python -m pip install --require-hashes -r requirements.lock
# --require-hashes makes pip refuse anything whose hash is not listed,
# so a reader cannot silently get a different build of the same version.
#
# Generated by scripts/make_lockfile.py against PyPI.  Regenerate with
# that script; do not hand-edit.
"""


def main():
    lines = [HEAD]
    for spec in PKGS:
        #  An entry is either "name==version" or that paired with the
        #  environment marker under which it is needed at all.
        spec, marker = spec if isinstance(spec, tuple) else (spec, "")
        name, ver = spec.split("==")
        spec = f"{spec} ; {marker}" if marker else spec
        try:
            d = json.loads(urllib.request.urlopen(
                f"https://pypi.org/pypi/{name}/{ver}/json", timeout=60).read())
            hs = sorted({f["digests"]["sha256"] for f in d["urls"]})
        except Exception as e:                              # noqa: BLE001
            print(f"{spec:32s} FAILED {type(e).__name__}: {e}", file=sys.stderr)
            lines.append(f"{spec}   # HASHES UNAVAILABLE -- see REPRODUCE.md")
            continue
        print(f"{spec:32s} {len(hs)} artefacts")
        lines.append(spec + " \\")
        lines += [f"    --hash=sha256:{h}" + (" \\" if i < len(hs) - 1 else "")
                  for i, h in enumerate(hs)]
    (ROOT / "requirements.lock").write_text("\n".join(lines) + "\n",
                                            encoding="utf-8")
    print(f"\nwrote {ROOT / 'requirements.lock'}")


if __name__ == "__main__":
    main()
