"""Regenerate requirements.lock: every dependency pinned by version AND by the
SHA-256 of every artefact PyPI serves for that version.

`requirements.txt` pins versions.  That is not enough for this repository:
round sixteen found that a BLAS thread-count change moved a bootstrap
percentile, and `verify_paper.py` tests rounding EQUALITY at the printed
precision rather than a tolerance.  A reader who installs "numpy==2.2.6" from
a different wheel, built against a different BLAS, can fail the checker while
computing nothing wrong.  Hashes close the first half of that gap; the
container definition and the thread pinning in REPRODUCE.md close the second.

    python scripts/make_lockfile.py          # writes ../requirements.lock
    python -m pip install --require-hashes -r requirements.lock
"""
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKGS = [
    "numpy==2.2.6", "pandas==2.3.1", "scipy==1.15.3", "scikit-learn==1.7.2",
    "matplotlib==3.10.5", "pyarrow==18.1.0", "joblib==1.5.2",
    "threadpoolctl==3.6.0", "python-dateutil==2.9.0.post0", "pytz==2025.2",
    "six==1.17.0", "cycler==0.12.1", "fonttools==4.59.0", "kiwisolver==1.4.8",
    "packaging==25.0", "pillow==11.3.0", "pyparsing==3.2.3",
    "contourpy==1.3.2", "tzdata==2025.2",
]
HEAD = """# requirements.lock -- every dependency pinned by version AND by the
# SHA-256 of every artefact PyPI serves for it.  Install with
#     python -m pip install --require-hashes -r requirements.lock
# --require-hashes makes pip refuse anything whose hash is not listed,
# so a reader cannot silently get a different build of the same version.
#
# Generated by scripts/make_lockfile.py against PyPI.  Regenerate with
# that script; do not hand-edit.
"""


def main():
    lines = [HEAD]
    for spec in PKGS:
        name, ver = spec.split("==")
        try:
            d = json.loads(urllib.request.urlopen(
                f"https://pypi.org/pypi/{name}/{ver}/json", timeout=60).read())
            hs = sorted({f["digests"]["sha256"] for f in d["urls"]})
        except Exception as e:                              # noqa: BLE001
            print(f"{spec:32s} FAILED {type(e).__name__}: {e}", file=sys.stderr)
            lines.append(f"{spec}   # HASHES UNAVAILABLE -- see REPRODUCE.md")
            continue
        print(f"{spec:32s} {len(hs)} artefacts")
        lines.append(spec + " \\")
        lines += [f"    --hash=sha256:{h}" + (" \\" if i < len(hs) - 1 else "")
                  for i, h in enumerate(hs)]
    (ROOT / "requirements.lock").write_text("\n".join(lines) + "\n",
                                            encoding="utf-8")
    print(f"\nwrote {ROOT / 'requirements.lock'}")


if __name__ == "__main__":
    main()
