"""make_highlights -- GENERATE submission/highlights.txt FROM THE MACROS.

Round twenty-two.  A reviewer found that Highlight 4 said the one-number
report misstates the sign of "a tenth" of the resolving cells while the
abstract said 5.6%.  Both were true of *something*: a tenth is the rate under
the NOMINAL band and 5.6% the rate under the calibrated one, which the article
says in bold is the only band its labels use.  They disagreed because the
Highlights are the one part of the submission the macro discipline never
covered -- a hand-written file, and the first line an editor reads.

This file closes that hole.  Every bullet is a template with `{macro}` slots
filled from `paper/numbers.tex`, so a highlight cannot state a number the
manuscript does not, and `check_highlights.py` still enforces the count and
the length.  Editing a bullet means editing the template here.

    python make_highlights.py            # write submission/highlights.txt
    python make_highlights.py --check    # fail if the file is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
NUMBERS = ROOT / "paper" / "numbers.tex"
OUT = ROOT / "submission" / "highlights.txt"
LIMIT = 85

#: Each bullet is a format string over macro names.  A macro that renders as
#: LaTeX (math mode, escaped percents) is cleaned to plain text, because
#: Elsevier's highlights field takes prose and not markup.
BULLETS = [
    "A field's incremental predictive performance is a surface, not one number",
    #  ROUND TWENTY-SIX.  The decomposition's headline changed when the split
    #  became an error stratum, so the bullet that advertises it changed too.
    "An exact decomposition separates analyst choices from resampling",
    #  ROUND TWENTY-SIX.  The sixth referee: this said "coverage-calibrated",
    #  and section 10.4 measures the coverage and finds it short of nominal
    #  everywhere in this corpus's configuration.  A highlight may not claim
    #  what the body disowns four sections later.
    "Simultaneous bands over the whole declared family, with coverage measured",
    #  ROUND TWENTY-SIX.  The sign-disagreement rate is withdrawn as a
    #  headline (section 6.4): under the three restrictions the paper's own
    #  argument implies it is one cell in forty-two.  What replaces it is the
    #  magnitude, which is the quantity that survives every restriction.
    "Resolved cells sit {madResolvedMedian} AUC from the one-number report",
    "A register's worth turns on the decision time and on which target is set",
]

PREAMBLE = """HIGHLIGHTS

GENERATED by scripts/make_highlights.py -- do not edit this file.

Elsevier allows three to five bullets, each at most 85 characters including
spaces.  Every number below is a macro from paper/numbers.tex, so a highlight
cannot state a figure the manuscript does not.  This file used to be written
by hand, and a reviewer found the consequence: a highlight quoting the
NOMINAL band's sign-disagreement rate beside an abstract quoting the
CALIBRATED one.  The first line an editor reads was the one line the
verification harness could not see.

`python scripts/check_highlights.py` re-derives every length below and fails
if one is wrong or over the limit.
"""


def macros():
    t = NUMBERS.read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r"\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}", t):
        v = m.group(2)
        #  plain text, not LaTeX: strip math mode, unescape the percent sign,
        #  and turn the thousands separator back into a comma
        v = v.replace("\\%", "%").replace("{,}", ",").replace("$", "")
        v = v.replace("\\,", " ").strip()
        out[m.group(1)] = v
    return out


def render():
    M = macros()

    class _D(dict):
        def __missing__(self, k):
            raise SystemExit("highlight names a macro that does not exist: %s"
                             % k)

    return [b.format_map(_D(M)) for b in BULLETS]


def build():
    items = render()
    over = [i for i in items if len(i) > LIMIT]
    if over:
        raise SystemExit("highlight over %d characters: %s"
                         % (LIMIT, over[0]))
    body = [PREAMBLE, ""]
    for i in items:
        body.append("[%d] %s" % (len(i), i))
    body += ["", "", "-- paste-ready, without the length prefixes --", ""]
    body += items
    return "\n".join(body) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = build()
    if a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            sys.exit("submission/highlights.txt is stale; run "
                     "scripts/make_highlights.py")
        print("highlights are current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    for i in render():
        print("  [%2d] %s" % (len(i), i))
    print("wrote %s" % OUT.name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
