"""verify_numbers -- CHECK EVERY MACRO AGAINST AN INDEPENDENT RE-DERIVATION.

Round nineteen.  The manuscript contains no numeric literals: every number is
a macro in `paper/numbers.tex`, generated by `scripts/make_numbers.py` from
`results/*.csv`.  That removes the class of defect in which the abstract and a
table disagree, and it introduces a new one: if `make_numbers.py` is wrong,
the whole manuscript is wrong consistently.

This file is the guard against that.  It re-derives each checked quantity from
the result file with code written against the DEFINITION rather than against
`make_numbers.py`, and compares.  Where a quantity is a straight lookup the
re-derivation is a different lookup; where it is a computation the
re-derivation is a different computation.

    python verify_numbers.py            # check
    python verify_numbers.py --list      # show every macro and its value

Exit status is non-zero if any checked macro disagrees, if any macro in the
manuscript is undefined, or if the manuscript carries a bare numeric literal
outside the generated files.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from common import RESULTS as _RESULTS  # noqa: E402
from common import fmt_fixed  # noqa: E402

#  The corruption suite (s13) runs this file against COPIES of the results,
#  the manuscript and the data, so that a corruption is never written to the
#  real tree.  The three environment variables are the only way it can do
#  that, and they default to the real tree.
import os  # noqa: E402
ROOT = Path(os.environ.get("FIELDVALUE_ROOT", HERE.parent))
RESULTS = Path(os.environ.get("FIELDVALUE_RESULTS", _RESULTS))
PAPER = Path(os.environ.get("FIELDVALUE_PAPER", ROOT / "paper"))
NUMBERS = PAPER / "numbers.tex"
MANUSCRIPT = PAPER / "specification_surfaces.tex"

#  The consistency conditions this file enforces BEYOND checking macros one
#  at a time: relations between numbers that no single macro expresses, so
#  that a manuscript in which every quantity is individually right and the set
#  of them is jointly impossible fails here.  The manuscript quotes the count
#  of these, so the list is the source of that number rather than a sentence
#  somebody has to remember to update.
CONDITIONS = (
    "every register-quality mechanism passed its executed train-only check",
    "no surface is labelled uniformly beneficial while carrying an "
    "unresolved cell",
    "no surface is labelled conditionally harmful while carrying a "
    "beneficial cell",
    "every region label is one of the six the manuscript defines",
    "the region labels partition the pairs",
    "the non-identification sweep still holds the AUC reduction at zero",
    "the adjudicated set of the practice pilot is exactly the screened-in set",
    "the case study's split partitions its cohort",
    "the pilot's frame is at least its sample, and equals it when every "
    "design weight is one",
    "every count in the PRISMA flow equals the macro the prose quotes it by",
    "every correction the main text cites exists in the register, and no "
    "correction is listed in two classes",
    #  round twenty; enforced in round20_verify.check
    "the disjoint functional-ANOVA components sum to one on every "
    "decomposition",
    "the weighted-mean rule's in-sample excess regret is zero, as the lemma "
    "requires",
    "no surface is labelled uniformly beneficial while carrying an "
    "unresolved or harmful cell under the whole-surface band",
    "no planned contrast reports a p-value of zero, or one below the floor "
    "the draw count permits",
    "the Holm adjustment of the planned contrasts reproduces from the raw "
    "p-values",
    "no rank-based instrument's reduction moves under a monotone "
    "recalibration",
    "every certificate for a non-rank-based instrument exhibits two ratios "
    "that actually differ",
    "the non-rank-based instrument whose reduction is invariant under the "
    "affine family really is non-rank-based",
    #  round twenty, second session: the two set identities the review names
    #  by name, and the replicate count behind the simulation's claim
    "the cells a region label ranges over are exactly the cells the "
    "simultaneous family that licenses it controls",
    "every decision rule is compared over the declared regret population, "
    "and no two rules over different cell sets",
    "the simulation behind the manuscript's coverage numbers ran at least "
    "the replicate count the manuscript claims",
    "the decision curve's intervals declare the basic construction the "
    "manuscript says every interval in it uses, and no simultaneous interval "
    "is narrower than its pointwise counterpart",
    "the harmful-point counts agree between the summary file that counts them "
    "and the band file they are counted from",
    "the one-number rule's median excess regret is zero in every instrument, "
    "which is a universal the prose asserts and only a count can hold",
)

FAILS = []
CHECKED = 0


def macros():
    t = NUMBERS.read_text(encoding="utf-8")
    return dict(re.findall(r"\\newcommand\{\\(\w+)\}\{(.*)\}", t))


def load(n):
    """Read a result file, compressed or not.  See spec.result_path."""
    for p in (RESULTS / n, RESULTS / (n + ".gz")):
        if p.exists():
            try:
                return pd.read_csv(p)
            except Exception:  # noqa: BLE001  -- an empty placeholder file
                return None
    return None


#  Every macro name eq() is called on, recorded at RUNTIME.  claim_registry
#  used to recover this by parsing the source for eq("literal", ...), which
#  misses every call whose name comes from a loop variable -- and both this
#  file and round20_verify.py check whole families that way, so the registry
#  reported 49 verified where the run checked 113.  A record the run itself
#  writes cannot be wrong about what the run did.
VERIFIED = []


def eq(name, want, M, note=""):
    """`want` is the string the macro should hold."""
    global CHECKED
    got = M.get(name)
    CHECKED += 1
    VERIFIED.append(name)
    if got is None:
        FAILS.append("%s: undefined in numbers.tex" % name)
        return
    if want is None:
        return
    if got.strip() != str(want).strip():
        FAILS.append("%s: numbers.tex has %r, re-derivation gives %r%s"
                     % (name, got, str(want), (" (" + note + ")") if note else ""))


def fmt_thousands(x):
    return "{:,}".format(int(round(float(x)))).replace(",", "{,}")


def fmt_pct(x, d=1):
    return fmt_fixed(100 * float(x), d) + "\\%"


def fmt_sig(x, d=4):
    #  math mode: see make_numbers.sig -- a text-mode minus is a hyphen
    v = fmt_fixed(float(x), d)
    return "$" + (v if v.startswith("-") else "+" + v) + "$"


def fmt_num(x, d=4):
    return fmt_fixed(float(x), d)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args(argv)
    if not NUMBERS.exists():
        sys.exit("paper/numbers.tex does not exist; run make_numbers.py")
    M = macros()
    if a.list:
        for k in sorted(M):
            print("  %-26s %s" % (k, M[k]))
        return

    # ---- the surface counts, re-derived from the surface itself ----------
    SUR = load("s01_surface.csv")
    if SUR is not None and len(SUR):
        eq("nPairs", fmt_thousands(SUR.groupby(["log", "target"]).ngroups), M)
        eq("nLogs", fmt_thousands(SUR.log.nunique()), M)
        eq("nDomains", fmt_thousands(SUR.domain.nunique()), M)
        eq("nLearners", fmt_thousands(SUR.learner.nunique()), M)
        eq("nSplits", fmt_thousands(SUR.split.nunique()), M)
        eq("nMetrics", fmt_thousands(SUR.metric.nunique()), M)
        eq("nSurfaceRows", fmt_thousands(len(SUR)), M)
        eq("nQuality",
           fmt_thousands(len(SUR[["quality", "level"]].drop_duplicates())), M)
        p14 = SUR[SUR.log == "BPIC14"]
        if len(p14):
            eq("cardF", fmt_thousands(p14.card_f.iloc[0]), M)
            #  BPIC14 carries TWO cohorts on purpose and the manuscript says
            #  so: \nCohortCorpus is the corpus cohort, admitted by the
            #  registered generic rules and measured here; \nCohort is the
            #  case study's, which uses this project's earlier eligibility
            #  rule and its own target and is verified against s08 below.
            #  Checking \nCohort against the corpus row is the mistake a
            #  reader would make, and the verifier used to make it too.
            eq("nCohortCorpus", fmt_thousands(p14.n.iloc[0]), M)

    #  the case study's own cohort, and the split that partitions it
    S8 = load("s08_facts.csv")
    if S8 is not None and len(S8):
        n_c = int(S8.n_cohort.iloc[0])
        eq("nCohort", fmt_thousands(n_c), M)
        n_tr, n_te = int(S8.n_train.iloc[0]), int(S8.n_test.iloc[0])
        if n_tr + n_te != n_c:
            FAILS.append("the case study's split does not partition its "
                         "cohort: %d + %d != %d" % (n_tr, n_te, n_c))

    # ---- the train-only checks -------------------------------------------
    CK = load("s01_trainonly.csv")
    if CK is not None and len(CK):
        eq("nTrainOnly", fmt_thousands(len(CK)), M)
        eq("nTrainOnlyPassed", fmt_thousands(int(CK.train_only.sum())), M)
        if int(CK.train_only.sum()) != len(CK):
            FAILS.append("a register-quality mechanism read the test half: "
                         "%d of %d checks failed"
                         % (len(CK) - int(CK.train_only.sum()), len(CK)))

    # ---- bootstrap and bands ---------------------------------------------
    #  s17's bands carry the same q_maxt as s02's -- the recentring shifts
    #  the band, not the quantile -- so either file verifies this, and the
    #  one the manuscript quotes is preferred.
    BN = load("s17_bands.csv")  # retired-ok: fallback: either band verifies this quantity, per the note above
    if BN is None or not len(BN):
        BN = load("s02_bands.csv")
    if BN is not None and len(BN):
        eq("maxTMedian", fmt_num(BN.q_maxt.median(), 2), M)
        eq("maxTMedianRatio",
           fmt_num(float(BN.q_maxt.median()) / 1.959963985, 2), M)
    FIE = load("s02_fieller.csv")
    if FIE is not None and len(FIE):
        eq("nFieller", fmt_thousands(len(FIE)), M)
        eq("nFiellerUnbounded",
           fmt_thousands(int((FIE.fieller_kind != "bounded").sum())), M)
    CF = load("s02_confirmatory.csv")
    if CF is not None and len(CF):
        eq("nConfirmReject",
           fmt_thousands(int((CF.p_holm < 0.05).sum())), M)

    # ---- the decomposition, re-derived from the sobol table --------------
    SOB = load("s03_sobol.csv")
    if SOB is not None and len(SOB):
        h = SOB[SOB.scale == "headroom"]
        for macro, axis in (("sobolRungPct", "rung"),
                            ("sobolLearnerPct", "learner"),
                            ("sobolQualityPct", "quality_level"),
                            ("sobolMetricPct", "metric"),
                            ("sobolSplitPct", "split")):
            v = h[h.axis == axis].S
            if len(v):
                eq(macro, fmt_pct(v.median()), M)
        inter = (h.S_total - h.S).clip(lower=0)
        eq("sobolInteractionPct", fmt_pct(inter.median()), M)

    #  the region labels come from the WHOLE-SURFACE band (s21) wherever it
    #  exists, which is the source make_numbers reads; s03's are the narrower
    #  family the correction withdraws.
    REG = load("s48w_regions.csv")
    if REG is None or not len(REG):
        REG = load("s03_regions.csv")
    if REG is not None and len(REG):
        eq("nPairsBanded", fmt_thousands(len(REG)), M)
        eq("nUniformlyBeneficial",
           fmt_thousands(int((REG.region == "uniformly beneficial").sum())), M)
        eq("nSignChanging",
           fmt_thousands(int((REG.region == "sign-changing").sum())), M)
        eq("nCondBeneficial",
           fmt_thousands(int((REG.region == "conditionally beneficial").sum())),
           M)
        eq("nUnresolvedPairs",
           fmt_thousands(int((REG.region == "unresolved").sum())), M)
        eq("rhoMedian", fmt_num(REG.rho.median(), 3), M)
        eq("nCondHarmful",
           fmt_thousands(int((REG.region == "conditionally harmful").sum())),
           M)
        #  the region labels must be consistent with the counts they summarise
        bad = REG[(REG.region == "uniformly beneficial")
                  & (REG.n_beneficial != REG.n_cells)]
        if len(bad):
            FAILS.append("a surface is labelled uniformly beneficial with "
                         "unresolved cells in it")
        bad = REG[(REG.region == "conditionally harmful")
                  & (REG.n_beneficial > 0)]
        if len(bad):
            FAILS.append("a surface is labelled conditionally harmful with a "
                         "beneficial cell in it")
        #  and the taxonomy must PARTITION: every pair carries exactly one of
        #  the six labels.  A seventh label appearing in the results and
        #  nowhere in the manuscript is the defect this condition exists to
        #  catch, because that is what happened this round.
        TAXONOMY = {"uniformly beneficial", "conditionally beneficial",
                    "conditionally harmful", "uniformly harmful",
                    "sign-changing", "unresolved"}
        stray = sorted(set(REG.region.astype(str)) - TAXONOMY)
        if stray:
            FAILS.append("region labels not in the manuscript's taxonomy: %s"
                         % ", ".join(stray))
        counted = int(sum((REG.region == r).sum() for r in TAXONOMY))
        if counted != len(REG):
            FAILS.append("the region taxonomy does not partition the pairs: "
                         "%d labelled of %d" % (counted, len(REG)))

    # ---- regret -----------------------------------------------------------
    #  ROUND TWENTY-TWO.  `misreportMedianPct' and `misreportMaxPct' used to
    #  be re-derived from s04, which computes the sign-disagreement rate a
    #  different way from s34 and disagrees with it on ten of nineteen pairs.
    #  Both were still defined, under one name, from two files.  The macros
    #  now come from s34 and are re-derived there (round21_verify); s04's own
    #  column is checked against itself under a name of its own so that the
    #  older analysis stays verifiable without lending its value to a
    #  manuscript macro.
    RU = load("s04_rules.csv")
    if RU is not None and len(RU):
        c = RU.one_number_misreport_conventional
        if not (0.0 <= float(c.median()) <= 1.0):
            FAILS.append("s04: a sign-disagreement rate outside [0, 1]")
    AX = load("s04_by_axis.csv")
    if AX is not None and len(AX):
        for macro, axis in (("flipRungPct", "rung"),
                            ("flipLearnerPct", "learner"),
                            ("flipMetricPct", "metric"),
                            ("flipSplitPct", "split"),
                            ("flipQualityPct", "quality")):
            v = AX[AX.axis == axis].flip_rate
            if len(v):
                eq(macro, fmt_pct(v.median()), M)

    # ---- the propositions, re-derived from their own output ---------------
    #  ROUND TWENTY.  Proposition 1's construction is regenerated by s29 with
    #  parameters the script asserts; s07's file is the round-nineteen
    #  construction and is the fallback only so a partial tree still verifies.
    #  The verifier must read the SAME source the generator does, or it
    #  reports a disagreement that is a disagreement between two correct
    #  constructions rather than an error.
    P1N = load("s29_prop1.csv")
    if P1N is not None and len(P1N) >= 2:
        gap = abs(float(P1N.R_ap.iloc[0]) - float(P1N.R_ap.iloc[1]))
        eq("propOneApGap", fmt_num(gap, 3), M,
           "recomputed from s29_prop1")
        eq("propOneSweepAp", fmt_num(gap, 3), M)
        if gap <= 0.1:
            FAILS.append("Proposition 1's two configurations no longer "
                         "separate R_AP")
        if abs(float(P1N.R_auc.iloc[0]) - float(P1N.R_auc.iloc[1])) > 1e-9:
            FAILS.append("Proposition 1's two configurations no longer "
                         "share R_AUC")
    else:
        P1 = load("s07_prop1.csv")
        if P1 is not None and len(P1):
            two = P1[P1.config.astype(str).isin(["0", "1"])]
            if len(two) == 2:
                gap = abs(float(two.R_ap.iloc[0]) - float(two.R_ap.iloc[1]))
                eq("propOneApGap", fmt_num(gap, 3), M)
            sw = P1[P1.config.astype(str) == "sweep"]
            if len(sw):
                eq("propOneSweepAp", fmt_num(sw.R_ap.max(), 3), M)
    P2 = load("s07_prop2.csv")
    if P2 is not None and len(P2):
        rb = P2[P2.rank_based == True]  # noqa: E712
        nb = P2[P2.rank_based == False]  # noqa: E712
        if len(rb) and float(rb.dR.max()) > 1e-12:
            FAILS.append("Proposition 2(i) fails: a rank-based metric moved R")
        if len(nb):
            eq("propTwoNonRankShift", fmt_num(nb.dR.max(), 3), M)

    # ---- the simulation ---------------------------------------------------
    #
    #  The coverage macros come from s31 when it has run and from s10 when it
    #  has not, because round20_numbers overrides them in exactly that case.
    #  A verifier that checked them against the other file would report a
    #  failure that is really a disagreement between two correct runs at
    #  different replicate counts, so the source is chosen the same way here.
    S31 = load("s31_coverage.csv")
    if S31 is not None and len(S31):
        core = S31[S31.estimand == "V_limit"]
        if "experiment" in core.columns:
            core = core[core.experiment == "core"]
        if len(core):
            eq("coverageNaiveMedian",
               fmt_pct(core[core.interval == "naive_pct"].coverage.median()), M)
            eq("coverageNestedMedian",
               fmt_pct(core[core.interval == "nested_pct"].coverage.median()),
               M)
            eq("coverageNestedMin",
               fmt_pct(core[core.interval == "nested_pct"].coverage.min()), M)
            eq("coverageNestedBasicMedian",
               fmt_pct(core[core.interval == "nested_basic"].coverage.median()),
               M)
            eq("coverageNestedBasicMin",
               fmt_pct(core[core.interval == "nested_basic"].coverage.min()), M)
            #  the two counts the prose states as claims about worlds
            piv = core.pivot_table(index="world", columns="interval",
                                   values="coverage")
            if {"nested_basic", "naive_pct"} <= set(piv.columns):
                eq("nWorldsNestedAtLeastNaive",
                   fmt_thousands(int((piv["nested_basic"]
                                      >= piv["naive_pct"] - 1e-12).sum())), M,
                   "recounted from s31_coverage")
                eq("nWorldsSim", fmt_thousands(int(len(piv))), M)
            if "nested_mofn" in piv.columns:
                mo = piv["nested_mofn"].dropna()
                bs = piv["nested_basic"].reindex(mo.index)
                eq("nWorldsMofnBeatsBasic",
                   fmt_thousands(int((mo > bs + 1e-12).sum())), M)
                eq("nWorldsMofnPriced", fmt_thousands(int(len(mo))), M)
            sp = core[(core.world == "sparse")
                      & (core.interval == "nested_basic")]
            if len(sp):
                eq("coverageSparseBasic", fmt_pct(sp.coverage.iloc[0]), M)
            #  the manuscript says the nested percentile interval's worst
            #  coverage anywhere in the six worlds is on the sparse register.
            #  That is a claim about which row is the minimum, not about a
            #  number, so no macro carries it and only a check can hold it.
            pc = core[core.interval == "nested_pct"]
            if len(pc) and str(pc.loc[pc.coverage.idxmin(), "world"]) != \
                    "sparse":
                FAILS.append(
                    "the manuscript says the nested percentile interval is "
                    "worst on the sparse world; in s31 it is worst on %s"
                    % pc.loc[pc.coverage.idxmin(), "world"])
        #  the replicate count the prose names must be the one that ran
        n_core = int(core.n.max()) if len(core) else 0
        if n_core and n_core < 1000:
            FAILS.append(
                "the simulation ran %d replicates per world; the review's "
                "P1.1 asks for at least 1000, and the manuscript says "
                "\\nSimReps" % n_core)
    else:
        SC = load("s10_coverage.csv")
        if SC is not None and len(SC):
            lim = SC[SC.estimand == "V_limit"]
            eq("coverageNaiveMedian",
               fmt_pct(lim[lim.interval == "naive"].coverage.median()), M)
            eq("coverageNestedMedian",
               fmt_pct(lim[lim.interval == "nested"].coverage.median()), M)
            eq("coverageNaiveMin",
               fmt_pct(lim[lim.interval == "naive"].coverage.min()), M)
            eq("coverageNestedMin",
               fmt_pct(lim[lim.interval == "nested"].coverage.min()), M)

    # ---- the case study ---------------------------------------------------
    L8 = load("s08_ladder.csv")
    if L8 is not None and len(L8):
        t1 = L8[L8.decision_time.astype(str).str.startswith("T1")]
        if len(t1):
            eq("VTone", fmt_sig(t1.V_auc.iloc[0]), M)
        g = L8[L8.baseline == "intake + group"]
        if len(g):
            eq("VTtwoGroup", fmt_sig(g.V_auc.iloc[0]), M)
        k = L8[L8.baseline.astype(str).str.contains("knowledge")]
        if len(k):
            eq("VTtwoKnow", fmt_sig(k.V_auc.iloc[0]), M)

    #  Every correction the main text cites by identifier must exist in the
    #  register, and the register's own class lists must not name one twice
    #  or leave one out.  Writing correction~C13 for the intercept-only
    #  headline when C13 is the `if and only if' correction is a citation to a
    #  real number that says the wrong thing, which no check for a missing
    #  macro would notice.
    PARTS = ROOT / "paper" / "parts"
    reg = PARTS / "app_corrections.tex"
    if reg.exists():
        text = reg.read_text(encoding="utf-8")
        #  the identifiers the register DEFINES are the ones inside its
        #  class-list parentheses
        #  A class DEFINES its members in the first parenthesised list after
        #  its own \paragraph heading.  A C-identifier in parentheses
        #  anywhere else -- the register's closing paragraph cites three --
        #  is a citation, not a second definition.
        blocks = re.split(r"\\paragraph\{Class ", text)[1:]
        defined = set()
        for b in blocks:
            m = re.search(r"\(((?:C\d+[,;]\s*)*C\d+)\)", b)
            if m:
                defined |= set(re.findall(r"C\d+", m.group(1)))
        cited = set()
        for f in sorted(PARTS.glob("*.tex")):
            if f.name == reg.name:
                continue
            cited |= set(re.findall(r"correction~?(C\d+)",
                                    f.read_text(encoding="utf-8")))
        missing = sorted(cited - defined)
        if missing:
            FAILS.append("the main text cites corrections the register does "
                         "not define: %s" % ", ".join(missing))
        #  and no identifier may appear in two different class lists
        seen, twice = set(), set()
        for b in blocks:
            m = re.search(r"\(((?:C\d+[,;]\s*)*C\d+)\)", b)
            for c in (re.findall(r"C\d+", m.group(1)) if m else []):
                (twice if c in seen else seen).add(c)
        if twice:
            FAILS.append("corrections listed in more than one class: %s"
                         % ", ".join(sorted(twice)))

    # ---- the practice pilot ----------------------------------------------
    S6 = load("s06_facts.csv")
    #  The frame is sum_h N_h over DISTINCT strata.  Summing the column over
    #  ROWS computes sum_h N_h * n_h, which put the reported frame at 54,910
    #  when it is 600, and the manuscript said so.  Re-derived here from the
    #  sample rather than read from the facts, and cross-checked against the
    #  weights: with every design weight equal to one, the frame and the
    #  sample are the same set and must be the same number.
    SAMP = load("s06_sample.csv")
    if S6 is not None and len(S6) and SAMP is not None and len(SAMP):
        per_h = SAMP.groupby("stratum").N_h.first()
        eq("nAuditFrame", fmt_thousands(per_h.sum()), M)
        eq("nAuditStrata", fmt_thousands(SAMP.stratum.nunique()), M)
        eq("nAuditSampled", fmt_thousands(len(SAMP)), M)
        if float(SAMP.weight.max()) == 1.0 and int(per_h.sum()) != len(SAMP):
            FAILS.append("every design weight is one, so the frame and the "
                         "sample must be the same number: %d vs %d"
                         % (per_h.sum(), len(SAMP)))
        if int(per_h.sum()) < len(SAMP):
            FAILS.append("the pilot's frame (%d) is smaller than its sample "
                         "(%d)" % (per_h.sum(), len(SAMP)))
        #  The PRISMA flow is a SECOND printing of numbers the prose also
        #  quotes, so the two can disagree -- and did: the table said 54,910
        #  records enumerated while Section 9.4 said 600, in one document.
        #  Every row of the flow that names a quantity with a macro is
        #  checked against that macro here.
        PR = load("s06_prisma.csv")
        if PR is not None and len(PR):
            flow = dict(zip(PR.step.astype(str), PR.n.astype(float)))
            for step, macro in (
                    ("records enumerated in the frame", "nAuditFrame"),
                    ("records sampled", "nAuditSampled"),
                    ("full text retrieved", "nAuditFullText"),
                    ("full text not retrieved", "nAuditNoFullText"),
                    ("screened in by the mechanical rule",
                     "nAuditScreenedIn")):
                if step in flow:
                    eq(macro, fmt_thousands(flow[step]), M,
                       note="PRISMA row %r" % step)
    A_in = ROOT / "data" / "audit2" / "adjudication_in.csv"
    A_out = ROOT / "data" / "audit2" / "adjudication_out.csv"
    if S6 is not None and len(S6) and A_in.exists() and A_out.exists():
        ai, ao = pd.read_csv(A_in), pd.read_csv(A_out)
        tp = int((ai.eligible == "yes").sum())
        fp = int((ai.eligible == "no").sum())
        fn_s = int((ao.eligible == "yes").sum())
        tn_s = int((ao.eligible == "no").sum())
        n_out = float(S6.n_screened_out.iloc[0])
        w = n_out / float(len(ao))
        sens = tp / (tp + fn_s * w)
        spec = (tn_s * w) / (tn_s * w + fp)
        eq("auditSens", fmt_num(sens, 3), M)
        eq("auditSpec", fmt_num(spec, 3), M)
        eq("auditPrec", fmt_num(tp / float(tp + fp), 3), M)
        eq("nAuditScreenedIn", fmt_thousands(len(ai)), M)
        eq("nAuditEligible", fmt_num(tp + fn_s * w, 1), M)
        #  the adjudication files must not disagree with the coding file
        C = load("s06_coding.csv")
        if C is not None:
            inc = set(C[C.status == "INCLUDED"].oa_id)
            if set(ai.oa_id) != inc:
                FAILS.append("the adjudicated screened-in set is not the "
                             "screened-in set: %d vs %d"
                             % (len(set(ai.oa_id)), len(inc)))

    # ---- round twenty ----------------------------------------------------
    #  The blueprint's Priority-0 and Priority-1 quantities, re-derived from
    #  the ROW-LEVEL result files rather than from the summary rows
    #  make_numbers reads.
    import round20_verify  # noqa: E402
    round20_verify.check(sys.modules[__name__], M)
    import round21_verify  # noqa: E402
    round21_verify.check(sys.modules[__name__], M)
    #  ---- round twenty-six -------------------------------------------
    #  Three conditions this round earned, one of them by breaking it.
    import round26_verify  # noqa: E402
    round26_verify.check(sys.modules[__name__], M)
    #  ---- round twenty-seven ---------------------------------------------
    #  Five conditions that hold BETWEEN objects: a table against a
    #  definition, a caption's ordinal against its own frame, a prose interval
    #  against the table it is read from, a pair's cell count against its
    #  log's, and a ladder against the cell the prose says it is on.  Each was
    #  a live contradiction that every per-macro check passed.
    import round27_verify  # noqa: E402
    round27_verify.check(sys.modules[__name__], M)

    # ---- the manuscript itself -------------------------------------------
    if MANUSCRIPT.exists():
        body = MANUSCRIPT.read_text(encoding="utf-8")
        body = re.sub(r"(?<!\\)%.*", "", body)          # strip comments
        used = set(re.findall(r"\\([A-Za-z]+)", body))
        undefined = sorted(k for k in used
                           if k in M or k.lower().startswith("n") and False)
        missing = sorted(k for k in re.findall(r"\\(n[A-Z]\w+|[a-z]+[A-Z]\w+)",
                                               body)
                         if k not in M and k not in _TEX_CONTROL)
        if missing:
            FAILS.append("macros used in the manuscript and not defined: %s"
                         % ", ".join(sorted(set(missing))[:12]))
        if "\\textbf{??}" in "".join(M.values()):
            n = sum(1 for v in M.values() if "??" in v)
            FAILS.append("%d macros are unresolved (\\textbf{??}); the "
                         "analysis has not been run to completion" % n)

    #  the record claim_registry reads: what this run actually checked,
    #  including every eq() whose macro name came from a loop variable.
    #  NOT wrapped in a try/except: a record that fails to write should
    #  say so, which is the lesson of the fifth defect this round found.
    body = "macro" + chr(10) + chr(10).join(sorted(set(VERIFIED)))
    (RESULTS / "verified_macros.csv").write_text(body + chr(10),
                                                 encoding="utf-8")

    print("verify_numbers: %d macros re-derived independently, "
          "%d consistency conditions enforced, %d failures"
          % (CHECKED, len(CONDITIONS) + len(round26_verify.CONDITIONS)
             + len(round27_verify.CONDITIONS),
             len(FAILS)))
    for f in FAILS:
        print("  FAIL  " + f)
    sys.exit(1 if FAILS else 0)


#  LaTeX control sequences the manuscript legitimately uses that look like
#  camel-case macros to the pattern above.
_TEX_CONTROL = {
    "documentclass", "usepackage", "urlstyle", "newtheorem", "theoremstyle",
    "includegraphics", "bibliographystyle", "bibliography", "newcommand",
    "textbf", "textit", "texttt", "emph", "citep", "citet", "linewidth",
    "mathrm", "operatorname", "leftarrow", "rightarrow", "quad", "qquad",
    "begin", "end", "section", "subsection", "paragraph", "label", "ref",
    "caption", "centering", "small", "item", "input", "appendix", "ead",
    "address", "author", "title", "journal", "keyword", "sep", "hspace",
    "vspace", "noindent", "hline", "toprule", "midrule", "bottomrule",
    "underbrace", "sum", "max", "leq", "geq", "neq", "subset", "cup", "cap",
    "times", "cdot", "sqrt", "frac", "hat", "bar", "mathcal", "mathbf",
    "mathbb", "sigma", "theta", "alpha", "beta", "rho", "lambda", "vartheta",
    "varphi", "psi", "pi", "Pr", "mathbf", "Bigl", "Bigr", "bigl", "bigr",
    "left", "right", "lceil", "rceil", "textrm", "text",
}

if __name__ == "__main__":
    main()
