"""verify_numbers -- CHECK EVERY MACRO AGAINST AN INDEPENDENT RE-DERIVATION.

Round nineteen.  The manuscript contains no numeric literals: every number is
a macro in `paper/numbers.tex`, generated by `scripts/make_numbers.py` from
`results/*.csv`.  That removes the class of defect in which the abstract and a
table disagree, and it introduces a new one: if `make_numbers.py` is wrong,
the whole manuscript is wrong consistently.

This file is the guard against that.  It re-derives each checked quantity from
the result file with code written against the DEFINITION rather than against
`make_numbers.py`, and compares.  Where a quantity is a straight lookup the
re-derivation is a different lookup; where it is a computation the
re-derivation is a different computation.

    python verify_numbers.py            # check
    python verify_numbers.py --list      # show every macro and its value

Exit status is non-zero if any checked macro disagrees, if any macro in the
manuscript is undefined, or if the manuscript carries a bare numeric literal
outside the generated files.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from common import RESULTS as _RESULTS  # noqa: E402

#  The corruption suite (s13) runs this file against COPIES of the results,
#  the manuscript and the data, so that a corruption is never written to the
#  real tree.  The three environment variables are the only way it can do
#  that, and they default to the real tree.
import os  # noqa: E402
ROOT = Path(os.environ.get("FIELDVALUE_ROOT", HERE.parent))
RESULTS = Path(os.environ.get("FIELDVALUE_RESULTS", _RESULTS))
PAPER = Path(os.environ.get("FIELDVALUE_PAPER", ROOT / "paper"))
NUMBERS = PAPER / "numbers.tex"
MANUSCRIPT = PAPER / "specification_surfaces.tex"

#  The consistency conditions this file enforces BEYOND checking macros one
#  at a time: relations between numbers that no single macro expresses, so
#  that a manuscript in which every quantity is individually right and the set
#  of them is jointly impossible fails here.  The manuscript quotes the count
#  of these, so the list is the source of that number rather than a sentence
#  somebody has to remember to update.
CONDITIONS = (
    "every register-quality mechanism passed its executed train-only check",
    "no surface is labelled uniformly beneficial while carrying an "
    "unresolved cell",
    "no surface is labelled conditionally harmful while carrying a "
    "beneficial cell",
    "every region label is one of the six the manuscript defines",
    "the region labels partition the pairs",
    "the non-identification sweep still holds the AUC reduction at zero",
    "the adjudicated set of the practice pilot is exactly the screened-in set",
    "the case study's split partitions its cohort",
)

FAILS = []
CHECKED = 0


def macros():
    t = NUMBERS.read_text(encoding="utf-8")
    return dict(re.findall(r"\\newcommand\{\\(\w+)\}\{(.*)\}", t))


def load(n):
    """Read a result file, compressed or not.  See spec.result_path."""
    for p in (RESULTS / n, RESULTS / (n + ".gz")):
        if p.exists():
            try:
                return pd.read_csv(p)
            except Exception:  # noqa: BLE001  -- an empty placeholder file
                return None
    return None


def eq(name, want, M, note=""):
    """`want` is the string the macro should hold."""
    global CHECKED
    got = M.get(name)
    CHECKED += 1
    if got is None:
        FAILS.append("%s: undefined in numbers.tex" % name)
        return
    if want is None:
        return
    if got.strip() != str(want).strip():
        FAILS.append("%s: numbers.tex has %r, re-derivation gives %r%s"
                     % (name, got, str(want), (" (" + note + ")") if note else ""))


def fmt_thousands(x):
    return "{:,}".format(int(round(float(x)))).replace(",", "{,}")


def fmt_pct(x, d=1):
    return ("%." + str(d) + "f\\%%") % (100 * float(x))


def fmt_sig(x, d=4):
    return ("%+." + str(d) + "f") % float(x)


def fmt_num(x, d=4):
    return ("%." + str(d) + "f") % float(x)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args(argv)
    if not NUMBERS.exists():
        sys.exit("paper/numbers.tex does not exist; run make_numbers.py")
    M = macros()
    if a.list:
        for k in sorted(M):
            print("  %-26s %s" % (k, M[k]))
        return

    # ---- the surface counts, re-derived from the surface itself ----------
    SUR = load("s01_surface.csv")
    if SUR is not None and len(SUR):
        eq("nPairs", fmt_thousands(SUR.groupby(["log", "target"]).ngroups), M)
        eq("nLogs", fmt_thousands(SUR.log.nunique()), M)
        eq("nDomains", fmt_thousands(SUR.domain.nunique()), M)
        eq("nLearners", fmt_thousands(SUR.learner.nunique()), M)
        eq("nSplits", fmt_thousands(SUR.split.nunique()), M)
        eq("nMetrics", fmt_thousands(SUR.metric.nunique()), M)
        eq("nSurfaceRows", fmt_thousands(len(SUR)), M)
        eq("nQuality",
           fmt_thousands(len(SUR[["quality", "level"]].drop_duplicates())), M)
        p14 = SUR[SUR.log == "BPIC14"]
        if len(p14):
            eq("cardF", fmt_thousands(p14.card_f.iloc[0]), M)
            #  BPIC14 carries TWO cohorts on purpose and the manuscript says
            #  so: \nCohortCorpus is the corpus cohort, admitted by the
            #  registered generic rules and measured here; \nCohort is the
            #  case study's, which uses this project's earlier eligibility
            #  rule and its own target and is verified against s08 below.
            #  Checking \nCohort against the corpus row is the mistake a
            #  reader would make, and the verifier used to make it too.
            eq("nCohortCorpus", fmt_thousands(p14.n.iloc[0]), M)

    #  the case study's own cohort, and the split that partitions it
    S8 = load("s08_facts.csv")
    if S8 is not None and len(S8):
        n_c = int(S8.n_cohort.iloc[0])
        eq("nCohort", fmt_thousands(n_c), M)
        n_tr, n_te = int(S8.n_train.iloc[0]), int(S8.n_test.iloc[0])
        if n_tr + n_te != n_c:
            FAILS.append("the case study's split does not partition its "
                         "cohort: %d + %d != %d" % (n_tr, n_te, n_c))

    # ---- the train-only checks -------------------------------------------
    CK = load("s01_trainonly.csv")
    if CK is not None and len(CK):
        eq("nTrainOnly", fmt_thousands(len(CK)), M)
        eq("nTrainOnlyPassed", fmt_thousands(int(CK.train_only.sum())), M)
        if int(CK.train_only.sum()) != len(CK):
            FAILS.append("a register-quality mechanism read the test half: "
                         "%d of %d checks failed"
                         % (len(CK) - int(CK.train_only.sum()), len(CK)))

    # ---- bootstrap and bands ---------------------------------------------
    #  s17's bands carry the same q_maxt as s02's -- the recentring shifts
    #  the band, not the quantile -- so either file verifies this, and the
    #  one the manuscript quotes is preferred.
    BN = load("s17_bands.csv")
    if BN is None or not len(BN):
        BN = load("s02_bands.csv")
    if BN is not None and len(BN):
        eq("maxTMedian", fmt_num(BN.q_maxt.median(), 2), M)
        eq("maxTMedianRatio",
           fmt_num(float(BN.q_maxt.median()) / 1.959963985, 2), M)
    FIE = load("s02_fieller.csv")
    if FIE is not None and len(FIE):
        eq("nFieller", fmt_thousands(len(FIE)), M)
        eq("nFiellerUnbounded",
           fmt_thousands(int((FIE.fieller_kind != "bounded").sum())), M)
    CF = load("s02_confirmatory.csv")
    if CF is not None and len(CF):
        eq("nConfirmReject",
           fmt_thousands(int((CF.p_holm < 0.05).sum())), M)

    # ---- the decomposition, re-derived from the sobol table --------------
    SOB = load("s03_sobol.csv")
    if SOB is not None and len(SOB):
        h = SOB[SOB.scale == "headroom"]
        for macro, axis in (("sobolRungPct", "rung"),
                            ("sobolLearnerPct", "learner"),
                            ("sobolQualityPct", "quality_level"),
                            ("sobolMetricPct", "metric"),
                            ("sobolSplitPct", "split")):
            v = h[h.axis == axis].S
            if len(v):
                eq(macro, fmt_pct(v.median()), M)
        inter = (h.S_total - h.S).clip(lower=0)
        eq("sobolInteractionPct", fmt_pct(inter.median()), M)

    REG = load("s03_regions.csv")
    if REG is not None and len(REG):
        eq("nPairsBanded", fmt_thousands(len(REG)), M)
        eq("nUniformlyBeneficial",
           fmt_thousands(int((REG.region == "uniformly beneficial").sum())), M)
        eq("nSignChanging",
           fmt_thousands(int((REG.region == "sign-changing").sum())), M)
        eq("nCondBeneficial",
           fmt_thousands(int((REG.region == "conditionally beneficial").sum())),
           M)
        eq("nUnresolvedPairs",
           fmt_thousands(int((REG.region == "unresolved").sum())), M)
        eq("rhoMedian", fmt_num(REG.rho.median(), 3), M)
        eq("nCondHarmful",
           fmt_thousands(int((REG.region == "conditionally harmful").sum())),
           M)
        #  the region labels must be consistent with the counts they summarise
        bad = REG[(REG.region == "uniformly beneficial")
                  & (REG.n_beneficial != REG.n_cells)]
        if len(bad):
            FAILS.append("a surface is labelled uniformly beneficial with "
                         "unresolved cells in it")
        bad = REG[(REG.region == "conditionally harmful")
                  & (REG.n_beneficial > 0)]
        if len(bad):
            FAILS.append("a surface is labelled conditionally harmful with a "
                         "beneficial cell in it")
        #  and the taxonomy must PARTITION: every pair carries exactly one of
        #  the six labels.  A seventh label appearing in the results and
        #  nowhere in the manuscript is the defect this condition exists to
        #  catch, because that is what happened this round.
        TAXONOMY = {"uniformly beneficial", "conditionally beneficial",
                    "conditionally harmful", "uniformly harmful",
                    "sign-changing", "unresolved"}
        stray = sorted(set(REG.region.astype(str)) - TAXONOMY)
        if stray:
            FAILS.append("region labels not in the manuscript's taxonomy: %s"
                         % ", ".join(stray))
        counted = int(sum((REG.region == r).sum() for r in TAXONOMY))
        if counted != len(REG):
            FAILS.append("the region taxonomy does not partition the pairs: "
                         "%d labelled of %d" % (counted, len(REG)))

    # ---- regret -----------------------------------------------------------
    RU = load("s04_rules.csv")
    if RU is not None and len(RU):
        c = RU.one_number_misreport_conventional
        eq("misreportMedianPct", fmt_pct(c.median()), M)
        eq("misreportMaxPct", fmt_pct(c.max()), M)
    AX = load("s04_by_axis.csv")
    if AX is not None and len(AX):
        for macro, axis in (("flipRungPct", "rung"),
                            ("flipLearnerPct", "learner"),
                            ("flipMetricPct", "metric"),
                            ("flipSplitPct", "split"),
                            ("flipQualityPct", "quality")):
            v = AX[AX.axis == axis].flip_rate
            if len(v):
                eq(macro, fmt_pct(v.median()), M)

    # ---- the propositions, re-derived from their own output ---------------
    P1 = load("s07_prop1.csv")
    if P1 is not None and len(P1):
        two = P1[P1.config.astype(str).isin(["0", "1"])]
        if len(two) == 2:
            gap = abs(float(two.R_ap.iloc[0]) - float(two.R_ap.iloc[1]))
            eq("propOneApGap", fmt_num(gap, 3), M)
            if gap <= 0.5:
                FAILS.append("Proposition 1's two configurations no longer "
                             "differ by more than 0.5 in R_AP")
        sw = P1[P1.config.astype(str) == "sweep"]
        if len(sw):
            eq("propOneSweepAp", fmt_num(sw.R_ap.max(), 3), M)
            if float(np.nanmax(np.abs(sw.R_auc))) > 1e-9:
                FAILS.append("Proposition 1's sweep no longer holds R_AUC at "
                             "zero")
    P2 = load("s07_prop2.csv")
    if P2 is not None and len(P2):
        rb = P2[P2.rank_based == True]  # noqa: E712
        nb = P2[P2.rank_based == False]  # noqa: E712
        if len(rb) and float(rb.dR.max()) > 1e-12:
            FAILS.append("Proposition 2(i) fails: a rank-based metric moved R")
        if len(nb):
            eq("propTwoNonRankShift", fmt_num(nb.dR.max(), 3), M)

    # ---- the simulation ---------------------------------------------------
    SC = load("s10_coverage.csv")
    if SC is not None and len(SC):
        lim = SC[SC.estimand == "V_limit"]
        eq("coverageNaiveMedian",
           fmt_pct(lim[lim.interval == "naive"].coverage.median()), M)
        eq("coverageNestedMedian",
           fmt_pct(lim[lim.interval == "nested"].coverage.median()), M)
        eq("coverageNaiveMin",
           fmt_pct(lim[lim.interval == "naive"].coverage.min()), M)
        eq("coverageNestedMin",
           fmt_pct(lim[lim.interval == "nested"].coverage.min()), M)

    # ---- the case study ---------------------------------------------------
    L8 = load("s08_ladder.csv")
    if L8 is not None and len(L8):
        t1 = L8[L8.decision_time.astype(str).str.startswith("T1")]
        if len(t1):
            eq("VTone", fmt_sig(t1.V_auc.iloc[0]), M)
        g = L8[L8.baseline == "intake + group"]
        if len(g):
            eq("VTtwoGroup", fmt_sig(g.V_auc.iloc[0]), M)
        k = L8[L8.baseline.astype(str).str.contains("knowledge")]
        if len(k):
            eq("VTtwoKnow", fmt_sig(k.V_auc.iloc[0]), M)

    # ---- the practice pilot ----------------------------------------------
    S6 = load("s06_facts.csv")
    A_in = ROOT / "data" / "audit2" / "adjudication_in.csv"
    A_out = ROOT / "data" / "audit2" / "adjudication_out.csv"
    if S6 is not None and len(S6) and A_in.exists() and A_out.exists():
        ai, ao = pd.read_csv(A_in), pd.read_csv(A_out)
        tp = int((ai.eligible == "yes").sum())
        fp = int((ai.eligible == "no").sum())
        fn_s = int((ao.eligible == "yes").sum())
        tn_s = int((ao.eligible == "no").sum())
        n_out = float(S6.n_screened_out.iloc[0])
        w = n_out / float(len(ao))
        sens = tp / (tp + fn_s * w)
        spec = (tn_s * w) / (tn_s * w + fp)
        eq("auditSens", fmt_num(sens, 3), M)
        eq("auditSpec", fmt_num(spec, 3), M)
        eq("auditPrec", fmt_num(tp / float(tp + fp), 3), M)
        eq("nAuditScreenedIn", fmt_thousands(len(ai)), M)
        eq("nAuditEligible", fmt_num(tp + fn_s * w, 1), M)
        #  the adjudication files must not disagree with the coding file
        C = load("s06_coding.csv")
        if C is not None:
            inc = set(C[C.status == "INCLUDED"].oa_id)
            if set(ai.oa_id) != inc:
                FAILS.append("the adjudicated screened-in set is not the "
                             "screened-in set: %d vs %d"
                             % (len(set(ai.oa_id)), len(inc)))

    # ---- the manuscript itself -------------------------------------------
    if MANUSCRIPT.exists():
        body = MANUSCRIPT.read_text(encoding="utf-8")
        body = re.sub(r"(?<!\\)%.*", "", body)          # strip comments
        used = set(re.findall(r"\\([A-Za-z]+)", body))
        undefined = sorted(k for k in used
                           if k in M or k.lower().startswith("n") and False)
        missing = sorted(k for k in re.findall(r"\\(n[A-Z]\w+|[a-z]+[A-Z]\w+)",
                                               body)
                         if k not in M and k not in _TEX_CONTROL)
        if missing:
            FAILS.append("macros used in the manuscript and not defined: %s"
                         % ", ".join(sorted(set(missing))[:12]))
        if "\\textbf{??}" in "".join(M.values()):
            n = sum(1 for v in M.values() if "??" in v)
            FAILS.append("%d macros are unresolved (\\textbf{??}); the "
                         "analysis has not been run to completion" % n)

    print("verify_numbers: %d macros re-derived independently, "
          "%d consistency conditions enforced, %d failures"
          % (CHECKED, len(CONDITIONS), len(FAILS)))
    for f in FAILS:
        print("  FAIL  " + f)
    sys.exit(1 if FAILS else 0)


#  LaTeX control sequences the manuscript legitimately uses that look like
#  camel-case macros to the pattern above.
_TEX_CONTROL = {
    "documentclass", "usepackage", "urlstyle", "newtheorem", "theoremstyle",
    "includegraphics", "bibliographystyle", "bibliography", "newcommand",
    "textbf", "textit", "texttt", "emph", "citep", "citet", "linewidth",
    "mathrm", "operatorname", "leftarrow", "rightarrow", "quad", "qquad",
    "begin", "end", "section", "subsection", "paragraph", "label", "ref",
    "caption", "centering", "small", "item", "input", "appendix", "ead",
    "address", "author", "title", "journal", "keyword", "sep", "hspace",
    "vspace", "noindent", "hline", "toprule", "midrule", "bottomrule",
    "underbrace", "sum", "max", "leq", "geq", "neq", "subset", "cup", "cap",
    "times", "cdot", "sqrt", "frac", "hat", "bar", "mathcal", "mathbf",
    "mathbb", "sigma", "theta", "alpha", "beta", "rho", "lambda", "vartheta",
    "varphi", "psi", "pi", "Pr", "mathbf", "Bigl", "Bigr", "bigl", "bigr",
    "left", "right", "lceil", "rceil", "textrm", "text",
}

if __name__ == "__main__":
    main()
